#!/usr/bin/env node

require('./config.js');

crypto = require('crypto');

if(process.argv.length != 4) {
    console.log('Usage: ' + process.argv[0] + ' "name@example.com" "pa$sP4ra$e"');
} else {
    var hash = new crypto.Hash('MD5');
    hash.update(process.argv[2] + process.argv[3] + secret);
    console.log('user = ', JSON.stringify({_id: process.argv[2], passwordHash: hash.digest('base64')}))
}


